-- Gender Analysis - 
-- Write a query to display the revenue generated by gender. Include the Gender (M/F) , total revenue, and total items purchased.

SELECT
    u.gender,
    SUM(oi.sale_price* o.num_of_item) AS total_revenue,
    SUM(o.num_of_item) AS total_items_purchased
FROM
    users u
INNER JOIN
    orders o ON u.id = o.user_id
INNER JOIN
    order_items oi ON o.order_id = oi.order_id
WHERE
    o.status NOT IN ('Cancelled', 'Returned')
GROUP BY
    u.gender;